services:
  # 1. ZOOKEEPER (Nécesaire pour l'image Confluent "Classique")
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: memora-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - memora-network

  # 2. KAFKA (Image Confluent Enterprise)
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: memora-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - memora-network

  # 3. POSTGRESQL + PGVECTOR (Reste inchangé, c'est le top)
  postgres:
    image: pgvector/pgvector:pg16
    container_name: memora-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=memora
      - POSTGRES_PASSWORD=memora
      - POSTGRES_DB=memora_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memora -d memora_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - memora-network

  # 4. KAFKA UI (Adapté pour Confluent)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: memora-kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-confluent
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - memora-network

  prometheus:
    image: prom/prometheus:latest
    container_name: memora-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - memora-network

  grafana:
    image: grafana/grafana:latest
    container_name: memora-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Mot de passe par défaut
    depends_on:
      - prometheus
    networks:
      - memora-network

    # ... (tes autres services)

  pgadmin:
    image: dpage/pgadmin4
    container_name: memora-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@memora.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - memora-network

volumes:
  postgres_data:

networks:
  memora-network:
    driver: bridge