global:
  scrape_interval: 5s # On aspire vite pour le test (en prod c'est plut√¥t 15s ou 1m)

scrape_configs:
  - job_name: 'memora-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Astuce pour taper sur ton Mac depuis Docker